/* converted on Sat Jul 25, 2020, 19:07 (UTC-03) by jison-to-w3c v0.50 which is Copyright (c) 2011-2020 by Gunther Rademacher <grd@gmx.net> */

sql ::= statement+ EOF

statement ::= ( ddl_statement | tcl_statement ) ";"

ddl_statement ::= createtable_statement
           | createschema_statement
           | droptable_statement
           | dropschema_statement
           | useschema_statement

tcl_statement ::= commit_statement
           | rollback_statement

createtable_statement ::= create_table NAME "(" table_constraint ( "," table_constraint )* ")"

createschema_statement ::= create_schema NAME

droptable_statement ::= drop_table NAME

dropschema_statement ::= drop_schema NAME

useschema_statement ::= use_schema NAME

commit_statement ::= COMMIT

rollback_statement ::= ROLLBACK

table_constraint ::= ( CONSTRAINT identifier? )? constraint
           | column

constraint ::= PRIMARY KEY "(" list_identifiers ")"
           | FOREIGN KEY "(" list_identifiers ")" REFERENCES foreign_reference

column ::= identifier datatype column_complement*

column_complement ::= ( CONSTRAINT identifier? )? column_constraint
           | NOT? NULL
           | AUTO_INCREMENT

column_constraint ::= ( PRIMARY | UNIQUE ) KEY
           | REFERENCES foreign_reference

foreign_reference ::= NAME "(" list_identifiers ")"

datatype ::= ( ENUM "(" string ( "," string )* ")" | ( CHAR | VARCHAR | VARCHAR2 | CHARACTER VARYING? ) size_typed? | ( CLOB | NCHAR | NVARCHAR | TEXT ) size? | LONGTEXT | MEDIUMTEXT | NCLOB | TINYTEXT ) collation?
           | ( DOUBLE PRECISION? | FLOAT | REAL ) size_float?
           | LONG ( ( NVARCHAR | VARCHAR ) size? collation? | VARBINARY size? )
           | TIME size? ( ( WITH | WITHOUT ) TIME ZONE )?
           | ( ( INT | INTEGER | MEDIUMINT | SMALLINT | TINYINT ) size? | BIGINT ) UNSIGNED?
           | ( DECIMAL | NUMBER | NUMERIC ) size_decimal?
           | ( BINARY | BIT | BLOB | TIMESTAMPTZ | TIMETZ | VARBINARY ) size?
           | ARRAY
           | BOOL
           | BOOLEAN
           | DATE
           | LONGBLOB
           | MEDIUMBLOB
           | OTHER
           | TINYBLOB
           | UUID

collation ::= COLLATE NAME

list_identifiers ::= identifier ( "," identifier )*

identifier ::= '"' NAME '"'
           | "`" NAME "`"
           | "[" NAME "]"
           | NAME

string ::= "'" CHARS "'"

size_decimal ::= "(" "*" ( "," S_INT )? ")"
           | size_float

size_float ::= "(" U_INT ( "," ( S_INT | U_INT ) )? ")"

size_typed ::= ( "(" U_INT ( BYTE | CHAR ) ")" | size )?

size ::= "(" U_INT ")"

create_table ::= CREATE ( TEMP | TEMPORARY )? TABLE

create_schema ::= CREATE SCHEMA

drop_table ::= DROP ( TEMP | TEMPORARY )? TABLE

drop_schema ::= DROP SCHEMA

use_schema ::= USE